linters:
  disable-all: true
  enable:
    - dupl
    - errcheck
    - exportloopref
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - nlreturn
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
  fast: false

linters-settings:
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - performance
      - style
    disabled-checks:
      - commentedOutCode
      - unnamedResult
      - whyNoLint
    settings:
      hugeParam:
        sizeThreshold: 512
  gocyclo:
    min-complexity: 15
  govet:
    enable:
      - fieldalignment
      - nilness
      - shadow
      - sigchanyzer
      - stringintconv
      - unusedwrite
  lll:
    line-length: 140
  misspell:
    locale: US
  nlreturn:
    block-size: 5
  revive:
    rules:
      - name: if-return
        disabled: true
  stylecheck:
    checks:
      ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - govet
        - lll
        - nlreturn
