name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.63
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: run shuffle tests
        run: go test -shuffle=on -timeout=3s -count 2 ./...
      - name: run the example
        working-directory: _example
        run: go run main.go
